# Generated by Django 5.1.7 on 2025-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Created", "created"), ("Deleted", "deleted")],
                        default="Created",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("link", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
            ],
            options={
                "db_table": "articles",
            },
        ),
        migrations.CreateModel(
            name="Guestbooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Created", "created"), ("Deleted", "deleted")],
                        default="Created",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("website", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=500)),
            ],
            options={
                "db_table": "guestbooks",
            },
        ),
        migrations.CreateModel(
            name="ProjectTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "project_tags",
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Created", "created"), ("Deleted", "deleted")],
                        default="Created",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("link", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[("Project", "project"), ("Package", "package")],
                        default="Project",
                        max_length=30,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_tags",
                        to="base_app.projecttags",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
    ]
