# Generated by Django 5.1.7 on 2025-03-18 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "display_admin_dashboard",
                    models.BooleanField(
                        default=True, help_text="Enable admin dashboard"
                    ),
                ),
                (
                    "display_navbar_image",
                    models.BooleanField(
                        default=True, help_text="Show image in navigation bar"
                    ),
                ),
                (
                    "multiple_themes",
                    models.BooleanField(
                        default=False, help_text="Allow multiple theme selection"
                    ),
                ),
                (
                    "enable_search",
                    models.BooleanField(
                        default=True, help_text="Enable search functionality"
                    ),
                ),
                (
                    "search_models",
                    models.JSONField(
                        blank=True, default=list, help_text="List of searchable models"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debug",
                    models.BooleanField(
                        default=False,
                        help_text="Enable debug mode (not recommended for production)",
                    ),
                ),
                (
                    "admin_fingerprint_signature",
                    models.CharField(
                        blank=True,
                        help_text="Security signature for admin authentication",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Setting",
                "verbose_name_plural": "Security Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github",
                    models.URLField(help_text="GitHub profile URL", max_length=255),
                ),
                (
                    "linkedin",
                    models.URLField(help_text="LinkedIn profile URL", max_length=255),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        help_text="Twitter profile URL (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        blank=True,
                        help_text="Signal number (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="Telegram handle (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Profile",
                "verbose_name_plural": "Social Profiles",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        choices=[("Dark", "dark"), ("Light", "light")],
                        default="Light",
                        help_text="Default site theme",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.CreateModel(
            name="PersonalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(help_text="Full name", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="Country of residence", max_length=100),
                ),
                (
                    "resume_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to resume (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "social",
                    models.OneToOneField(
                        help_text="Social media profiles",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_settings",
                        to="base_app.socialprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Setting",
                "verbose_name_plural": "Personal Settings",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_settings",
                        to="base_app.adminconfiguration",
                    ),
                ),
                (
                    "personal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_settings",
                        to="base_app.personalsettings",
                    ),
                ),
                (
                    "security",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_settings",
                        to="base_app.security",
                    ),
                ),
                (
                    "theme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_settings",
                        to="base_app.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
