# Generated by Django 5.1.7 on 2025-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0002_adminconfiguration_security_socialprofile_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttags",
            name="description",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
