# Generated by Django 5.1.7 on 2025-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0003_projecttags_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(
                choices=[("project", "Project"), ("package", "Package")],
                default="project",
                max_length=30,
            ),
        ),
    ]
