# Generated by Django 5.1.7 on 2025-04-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0005_personalsettings_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalsettings",
            name="social",
            field=models.OneToOneField(
                blank=True,
                help_text="Social media profiles",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_settings",
                to="base_app.socialprofile",
            ),
        ),
    ]
