# Generated by Django 5.1.7 on 2025-04-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0006_alter_personalsettings_social"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="adminconfiguration",
            table="admin_configurations",
        ),
        migrations.AlterModelTable(
            name="personalsettings",
            table="personal_settings",
        ),
        migrations.AlterModelTable(
            name="security",
            table="security",
        ),
        migrations.AlterModelTable(
            name="sitesettings",
            table="site_settings",
        ),
        migrations.AlterModelTable(
            name="socialprofile",
            table="social_profiles",
        ),
        migrations.AlterModelTable(
            name="theme",
            table="themes",
        ),
    ]
