# Generated by Django 5.1.7 on 2025-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0007_alter_adminconfiguration_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalsettings",
            name="status",
            field=models.CharField(
                choices=[("Created", "created"), ("Deleted", "deleted")],
                default="Created",
                max_length=30,
            ),
        ),
    ]
