# Generated by Django 5.1.7 on 2025-04-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0008_personalsettings_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="configuration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_settings_configuration",
                to="base_app.adminconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="personal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_settings_personal",
                to="base_app.personalsettings",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="security",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_settings_security",
                to="base_app.security",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="theme",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_settings_theme",
                to="base_app.theme",
            ),
        ),
    ]
