# Generated by Django 5.1.7 on 2025-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0010_alter_sitesettings_configuration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="default_theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="light",
                help_text="Default site theme",
                max_length=30,
            ),
        ),
    ]
