# Generated by Django 5.1.7 on 2025-04-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0011_alter_theme_default_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalsettings",
            name="social",
            field=models.OneToOneField(
                default=None,
                help_text="Social media profiles",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_settings",
                to="base_app.socialprofile",
            ),
            preserve_default=False,
        ),
    ]
