name: Lint

on:
  push:
    branches: ['*']
  # pull_request:
  #   branches: ['*']

jobs:
  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'client/yarn.lock'

      - name: Install Client Dependencies
        run: |
          cd client
          yarn install

      - name: Lint Client
        run: |
          cd client
          yarn lint

  lint-server:
    name: Lint Server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Server Dependencies
        run: |
          cd server
          poetry install

      - name: Lint Server with Black
        run: |
          cd server
          poetry run black . --exclude=__init__.py --check

      - name: Lint Server with Flake8
        run: |
          cd server
          poetry run flake8 . --exclude=__init__.py
